/**
 * The second version of API
 * Describe the fundamental concept of DFD(Documentation-First Developmemt).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 0417taehyun@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("BookApi", () => {
  let instance: api.BookApi
  beforeEach(function() {
    instance = new api.BookApi(config)
  });

  test("getBooksBooksGet", () => {
    return expect(instance.getBooksBooksGet({})).resolves.toBe(null)
  })
})

